export const weatherIconCode = {
  1000: { name: "Clear", src: "assets/Clear.png" },
  1100: { name: "Mostly Clear", src: "assets/MostlyClear.png" },
  1101: { name: "Partly Cloudy", src: "assets/partlycloudy.png" },
  1102: { name: "Mostly Cloudy", src: "assets/mostlycloudy.png" },
  1001: { name: "Cloudy", src: "assets/cloudy.png" },
  2000: { name: "Fog", src: "assets/fog.png" },
  2100: { name: "Light Fog", src: "assets/lightfog.png" },
  4000: { name: "Drizzle", src: "assets/drizzle.png" },
  4001: { name: "Rain", src: "assets/rain.png" },
  4200: { name: "Light Rain", src: "assets/lightrain.png" },
  4201: { name: "Heavy Rain", src: "assets/heavyrain .png" },
  5000: { name: "Snow", src: "assets/snow.png" },
  5001: { name: "Flurries", src: "assets/flurries.png" },
  5100: { name: "Light Snow", src: "assets/lightsnow.png" },
  5101: { name: "Heavy Snow", src: "assets/heavyrain.png" },
  6000: { name: "Freezing Drizzle", src: "assets/freezingdrizzle.png" },
  6001: { name: "Freezing Rain", src: "assets/freezingrain.png" },
  6200: {
    name: "Light Freezing Rain",
    src: "assets/lightfreezingdrizzle.png",
  },
  6201: { name: "Heavy Freezing Rain", src: "assets/heavyfreezingrain.png" },
  7000: { name: "Ice Pellets", src: "assets/icepellets.png" },
  7101: { name: "Heavy Ice Pellets", src: "assets/heavyicepellets.png" },
  7102: { name: "Light Ice Pellets", src: "assets/lighticepellets.png" },
  8000: { name: "Thunderstorm", src: "assets/thunderstorm.png" },
};
